# Generated by Django 5.2.8 on 2025-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_limite',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_validade',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
