# Generated by Django 5.2.8 on 2025-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emprestimo_data_limite_reserva_data_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bloqueado_ate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
